
CREATE TABLE "author" (
  "auID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "authorOfInterest" INTEGER DEFAULT 0,
  "modified" TEXT
);

CREATE TABLE "authorName" (
  "anID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "auID" INTEGER NOT NULL,
  "default" INTEGER DEFAULT 0,
  "lastName" TEXT,
  "firstName" TEXT,
  "initials" TEXT,
  "collectiveName" TEXT,
  FOREIGN KEY("auID") REFERENCES "author"("auID") ON DELETE CASCADE
);

CREATE TABLE "article" (
  "arID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "PMID" TEXT UNIQUE,
  "title" TEXT NOT NULL,
  "journal" TEXT,
  "year" INTEGER,
  "month" TEXT,
  "day" INTEGER
);

CREATE TABLE "coAuthor" (
  "arID" INTEGER,
  "auID" INTEGER,
  "authorOrder" INTEGER,
  "anID" INTEGER,
  PRIMARY KEY ("arID", "auID", "authorOrder"),
  FOREIGN KEY("arID") REFERENCES "article"("arID") ON DELETE CASCADE,
  FOREIGN KEY("auID") REFERENCES "author"("auID") ON DELETE CASCADE,
  FOREIGN KEY("anID") REFERENCES "authorName"("anID") ON DELETE CASCADE
);

CREATE TABLE "affiliation" (
  "afID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "affiliation" TEXT NOT NULL
);

CREATE TABLE "author_affiliation" (
  "aafID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "arID" INTEGER NOT NULL,
  "auID" INTEGER NOT NULL,
  "afID" INTEGER NOT NULL,
  FOREIGN KEY("arID") REFERENCES "article"("arID") ON DELETE CASCADE,
  FOREIGN KEY("auID") REFERENCES "author"("auID") ON DELETE CASCADE,
  FOREIGN KEY("afID") REFERENCES "affiliation"("afID") ON DELETE CASCADE
);

CREATE TABLE "meshLink" (
 "uid" INTEGER PRIMARY KEY,
 "meshui" TEXT UNIQUE NOT NULL
);

CREATE TABLE "meshTerm" (
 "mteID" INTEGER PRIMARY KEY AUTOINCREMENT,
 "meshui" TEXT NOT NULL,
 "meshterm" TEXT NOT NULL,
 FOREIGN KEY("meshui") REFERENCES "meshLink"("meshui") ON DELETE CASCADE
);

CREATE TABLE "meshTree" (
 "mtrID" INTEGER PRIMARY KEY AUTOINCREMENT,
 "uid" INTEGER,
 "treenum" TEXT UNIQUE, 
 FOREIGN KEY("uid") REFERENCES "meshLink"("uid") ON DELETE CASCADE
);

CREATE TABLE "mesh_article" (
  "maID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "arID" INTEGER NOT NULL,
  "meshui" TEXT NOT NULL,
  "descriptorMajor" INTEGER,
  FOREIGN KEY("arID") REFERENCES "article"("arID") ON DELETE CASCADE,
  FOREIGN KEY("meshui") REFERENCES "meshLink"("meshui") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "idx_treenum" ON "meshTree" ("treenum");
