#' Add authors to the database
#'
#' @param authors The coAuthors data frame generated by ncbi_authorPublications
#' @param dbInfo Connection to a Colabnet database
#' @param commit (Default = TRUE). Commit changes to the database automatically
#'
#' @import sqlife
#' @import dplyr
#'
#' @return Data frame with new, updated and existing author info
#' @export
#'
dbAddAuthors <- function(authors, dbInfo, commit = T) {
  conn <- dbGetConn(dbInfo, inherit = !commit)
  # Get all distinct author names, but assume same author is last name and initials are the same
  authors <- authors |>
    select(
      lastName,
      firstName,
      initials,
      collectiveName,
      tempId,
      def = default
    ) |>
    distinct()

  authors <- authors |>
    left_join(
      tbl(conn, "authorName"),
      by = c("lastName", "firstName", "initials", "collectiveName"),
      copy = TRUE
    ) |>
    collect()

  # Check which authors already exist in the DB (nothing to do)
  existing <- authors |>
    group_by(tempId) |>
    filter(!is.na(anID)) |>
    ungroup() |>
    mutate(status = "existing")

  # Check authors that are already in the DB, but an alternative version of the name popped up
  updated <- authors |>
    group_by(tempId) |>
    filter(!sum(is.na(anID)) %in% c(0, n())) |>
    ungroup()

  # Add those alternative names to the DB with same author ID
  if (nrow(updated) > 0) {
    updated <- updated |>
      group_by(tempId) |>
      mutate(auID = min(auID, na.rm = T)) |>
      ungroup() |>
      filter(is.na(anID))

    updated <- tbl_update(updated, conn, "authorName") |>
      mutate(status = "updated")

    q <- dbExecute(
      conn,
      sprintf(
        "UPDATE author SET modified = '%s' WHERE auID IN (%s)",
        timeStamp(),
        paste(unique(updated$auID), collapse = ",")
      )
    )
  }

  # Add authors who are not yet in the DB
  new <- authors |>
    group_by(tempId) |>
    filter(all(is.na(anID))) |>
    ungroup() |>
    select(-auID)

  if (nrow(new) > 0) {
    # Create new author IDs
    auID <- data.frame(
      modified = rep(timeStamp(), new$tempId |> n_distinct())
    )
    auID <- tbl_insert(auID, conn, "author") |> select(auID)

    auID$tempId <- unique(new$tempId)
    new <- new |>
      left_join(auID, by = "tempId") |>
      select(
        auID,
        default = def,
        lastName,
        firstName,
        initials,
        collectiveName
      )

    # Add author names
    new <- tbl_insert(new, conn, "authorName") |>
      mutate(status = "new")
  }

  dbFinish(conn)

  return(bind_rows(new, updated, existing) |> select(-tempId))
}

#' Remove authors and their articles from the database
#'
#' @param auIDs auIDs to remove. Co-authors who are not and authorOfInterest and
#' do not appear in other non-removed articles, are removed too
#' @param dbInfo Connection to a Colabnet database
#' @param commit (Default = TRUE). Commit changes to the database automatically
#'
#' @import dplyr
#'
#' @return data frame with all auID and arID that were removed
#' @export
#'
dbDeleteAuthors <- function(auIDs, dbInfo, commit = T) {
  conn <- dbGetConn(dbInfo, inherit = !commit)

  # Get all articles and authors to remove
  toRemove <- tbl(conn, "coAuthor") |>
    select(arID, auID1 = auID) |>
    left_join(
      tbl(conn, "author") |> select(auID1 = auID, authorOfInterest),
      by = "auID1"
    ) |>
    left_join(
      tbl(conn, "coAuthor") |> select(arID, auID2 = auID),
      by = "arID"
    ) |>
    filter(
      auID2 %in% local(auIDs),
      auID1 %in% local(auIDs) | authorOfInterest == 0
    ) |>
    select(auID = auID1, arID) |>
    collect()

  # Make sure not to remove co-authors who apprear in articles that are not being deleted
  toKeep <- tbl(conn, "coAuthor") |>
    filter(
      !arID %in% local(toRemove$arID),
      auID %in% local(toRemove$auID)
    ) |>
    pull(auID) |>
    unique()

  toRemove <- toRemove |> filter(!auID %in% toKeep)

  # Delete authors
  tbl_delete(
    toRemove |> select(auID) |> distinct(),
    conn,
    "author",
    returnData = F
  )

  # Delete articles
  tbl_delete(
    toRemove |> select(arID) |> distinct(),
    conn,
    "article",
    returnData = F
  )

  dbFinish(conn)

  return(toRemove)
}

#' Insert MeSH info into the ColabNet database
#'
#' @param values vector of MeSH values to search for
#' @param type The type needs to be 'meshui' (MeSH ui), 'treenum' (tree number) or 'uid' (MeSH Entrez uid)
#' @param dbInfo Connection to a Colabnet database
#' @param commit (Default = TRUE). Commit changes to the database automatically
#'
#' @import dplyr
#'
#' @return data frame with all uid and meshui inserted into the database (including intermediate tree nodes)
#' @export
#'
dbAddMesh <- function(values, type, dbInfo, commit = T) {
  conn <- dbGetConn(dbInfo, inherit = !commit)

  meshInfo <- ncbi_meshInfo(values, type)

  # Check with intermediate tree nodes (treenum) are missing to get to root
  missingNodes <- missingTreeNums(meshInfo$meshTree$treenum)

  # Check DB which missing treenums (intermediate nodes) are already in the DB
  knownTreenums <- tbl(conn, "meshTree") |>
    filter(treenum %in% local(missingNodes)) |>
    pull(treenum)

  # Get info on remaining missing nodes
  missingNodes <- setdiff(missingNodes, knownTreenums)

  # Iteratively add missing nodes
  #  Iteration needed because some IDs have multple treenums
  while (length(missingNodes) > 0) {
    # Seach NCBI and add results
    newNodes <- ncbi_meshInfo(missingNodes, type = "treenum")
    meshInfo$meshTerms <- rbind(meshInfo$meshTerms, newNodes$meshTerms)
    meshInfo$meshTree <- rbind(meshInfo$meshTree, newNodes$meshTree)

    # Again check if there are missing links in the new nodes
    missingNodes <- missingTreeNums(meshInfo$meshTree$treenum)
    knownTreenums <- c(
      knownTreenums,
      tbl(conn, "meshTree") |>
        filter(treenum %in% local(missingNodes)) |>
        pull(treenum)
    )

    missingNodes <- setdiff(missingNodes, knownTreenums)
  }

  toAdd <- setdiff(meshInfo$meshTree$treenum, knownTreenums)

  if (length(toAdd) > 0) {
    # Only add new tree data
    meshInfo$meshTree <- meshInfo$meshTree |> filter(treenum %in% toAdd)
    meshInfo$meshTerms <- meshInfo$meshTerms |>
      filter(meshui %in% meshInfo$meshTree$meshui)

    # Find new and existing
    meshLinks <- meshInfo$meshTree |>
      select(uid, meshui) |>
      distinct() |>
      mutate(uid = as.integer(uid))
    existing <- tbl(conn, "meshLink") |>
      filter(uid %in% local(meshLinks$uid)) |>
      select(uid, meshui) |>
      collect()
    new <- meshLinks |> filter(!uid %in% existing$uid)

    # Insert new MeSH links
    tbl_insert(new |> select(uid, meshui), conn, "meshLink", returnData = F)

    # Insert new MeSH Terms
    meshTerms <- meshInfo$meshTerms |>
      select(meshui, meshterm) |>
      distinct() |>
      filter(!meshui %in% existing$meshui) |>
      select(meshui, meshterm)

    tbl_insert(meshTerms, conn, "meshTerm", returnData = F)

    # Insert new MeSH Tree branches
    meshTree <- meshInfo$meshTree |>
      select(uid, treenum) |>
      distinct()

    meshTree <- meshTree |>
      filter(!uid %in% existing$uid) |>
      select(uid, treenum)

    tbl_insert(meshTree, conn, "meshTree", returnData = F)
  }

  dbFinish(conn)

  return(bind_rows(
    new |> mutate(status = "new"),
    existing |> mutate(status = "existing")
  ))
}

#' Tell the colabNet app an update has been made and it needs to refresh
#'
#' @param action (Integer) The code of the action
#'  - 0 = new database init
#'  - 1 = add data
#'  - 2 = delete data
#' @param dbInfo Connection to a Colabnet database
#' @param commit (Default = TRUE). Commit changes to the database automatically
#'
#' @import RSQLite
#'
#' @return The uID from inserted row into updateData
#' @export
#'
dbFlagUpdate <- function(action, dbInfo, commit = T) {
  action <- data.frame(
    timestamp = format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
    action = as.integer(action)
  )

  if (!action$action %in% 0:2) {
    stop("The action value must be an integer between 0 - 2")
  }

  conn <- dbGetConn(dbInfo, inherit = !commit)
  uID <- tbl_insert(action, conn, "updateData") |> pull(uID)
  dbFinish(conn)

  return(uID)
}

#' Add authors to the database
#'
#' @param authorPublications List of data frames geneated by ncbi_publicationDetails()
#' @param flagUpdate Default= T, set an update flag in the DB so the app will refresh once completed
#' @param dbInfo Connection to a Colabnet database
#' @param commit (Default = TRUE). Commit changes to the database automatically
#'
#' @import RSQLite
#' @import dplyr
#'
#' @return Data is inserted into the DB returning a list the author's aritcles (arID and PMID)
#' @export
#'
dbAddAuthorPublications <- function(
  authorPublications,
  matchOnFirst = F,
  flagUpdate = T,
  dbInfo,
  commit = T
) {
  if (nrow(authorPublications$articles) == 0) {
    return(data.frame(
      arID = integer(),
      PMID = integer(),
      status = character()
    ))
  }

  conn <- dbGetConn(dbInfo, inherit = !commit)

  ### ADD ARTICLES
  articles <- authorPublications$articles

  # Check which articles are already in the database
  existing <- tbl(conn, "article") |>
    filter(PMID %in% local(articles$PMID)) |>
    select(arID, PMID) |>
    collect() |>
    mutate(status = "existing")

  new <- articles |> filter(!PMID %in% existing$PMID)

  if (nrow(new) > 0) {
    new <- tbl_insert(new, conn, "article") |>
      select(arID, PMID) |>
      mutate(status = "new")
  } else {
    new <- data.frame()
  }

  arInfo <- bind_rows(new, existing)

  # Stop if no new articles were found
  if (all(arInfo$status == "existing")) {
    # Check if the author was already marked as one of interest
    if (matchOnFirst) {
      auID <- tbl(conn, "authorName") |>
        filter(
          lastName %in% local(authorPublications$author$lastName),
          firstName %in% local(authorPublications$author$firstName)
        ) |>
        pull(auID) |>
        unique()
    } else {
      auID <- tbl(conn, "authorName") |>
        filter(
          lastName %in% local(authorPublications$author$lastName),
          initials %in% local(authorPublications$author$initials)
        ) |>
        pull(auID) |>
        unique()
    }

    if (length(auID) != 1) {
      dbFinish(
        conn,
        error = ifelse(
          length(auID) > 1,
          "Ambiguous author of interest",
          "No match on author first and last name"
        )
      )
    }

    . <- tbl_update(
      data.frame(auID = auID, authorOfInterest = 1),
      conn,
      "author"
    )

    action <- data.frame(
      timestamp = format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
      action = as.integer(1)
    )

    . <- tbl_insert(action, conn, "updateData")

    dbFinish(conn)

    return(arInfo %>% mutate(auID = {{ auID }}))
  }

  # Only continue with new article data from authorPublications
  authorPublications <- filter_PMID(authorPublications, PMIDs = new$PMID)

  ### ADD (CO)AUTHOR INFO
  auInfo <- dbAddAuthors(
    authorPublications$coAuthors,
    dbInfo = conn,
    commit = F
  )

  # Set authorOfInterest to TRUE to distinguish from co-authors
  auID <- auInfo |>
    filter(
      lastName %in% authorPublications$author$lastName,
      initials %in% authorPublications$author$initials
    ) |>
    pull(auID) |>
    unique()

  # TODO This is a bit of a hack if length(auID) > 1
  # IN this case the author has a conflict with last name + initials with another
  if (matchOnFirst | length(auID) > 1) {
    auID <- auInfo |>
      filter(
        lastName %in% authorPublications$author$lastName,
        firstName %in% authorPublications$author$firstName
      ) |>
      pull(auID) |>
      unique()
  }

  if (length(auID) != 1) {
    dbFinish(
      conn,
      error = ifelse(
        length(auID) > 1,
        "Ambiguous author of interest",
        "No match on author first and last name"
      )
    )
  }

  . <- tbl_update(
    data.frame(auID = auID, authorOfInterest = 1),
    conn,
    "author"
  )

  # ADD AFFILIATIONS
  affiliations <- authorPublications$affiliations

  existing <- tbl(conn, "affiliation") |>
    filter(affiliation %in% local(unique(affiliations$affiliation))) |>
    collect()
  new <- affiliations |>
    select(affiliation) |>
    distinct() |>
    filter(!affiliation %in% existing$affiliation)

  if (nrow(new) > 0) {
    new <- tbl_insert(
      new |> select(affiliation),
      conn,
      "affiliation"
    )
  }

  afInfo <- bind_rows(new, existing)

  # ADD ARTICLE (CO)AUTHOR INFO AND AFFILIATIONS
  arAuAf <- authorPublications$coAuthors |>
    left_join(
      auInfo,
      by = c("lastName", "firstName", "initials", "collectiveName"),
      na_matches = "na"
    ) |>
    left_join(
      authorPublications$affiliations,
      by = c("PMID", "authorOrder")
    ) |>
    left_join(afInfo, by = "affiliation") |>
    left_join(arInfo, by = "PMID")

  # Filter out articles that are already in the database (via other author of interest)
  coAuthors <- arAuAf |>
    select(arID, auID, authorOrder, anID) |>
    distinct() |>
    tbl_insert(conn, "coAuthor")

  # Sometimes affiliations are not provided so remove the empty ones
  affiliations <- arAuAf |>
    select(arID, auID, afID) |>
    distinct() |>
    filter(!is.na(afID)) |>
    tbl_insert(conn, "author_affiliation")

  # ADD MESH INFO
  # First make sure the MeSH tree is complete for any new terms
  meshDescriptors <- authorPublications$meshDescriptors |>
    left_join(arInfo, by = "PMID") |>
    filter(status == "new")

  if (nrow(meshDescriptors) > 0) {
    meshui <- unique(meshDescriptors$DescriptorUI)

    # The check tags male (D008297) and female (D005260) will be ignored as they
    #  are not part of the MeSH Tree
    #  https://www.nlm.nih.gov/tsd/cataloging/MeSH_CatPractices.html
    meshui <- meshui[!meshui %in% c("D008297", "D005260")]

    # Add nymissing MeSH terms / Tree branches to the database
    if (length(meshui) > 0) {
      result <- dbAddMesh(meshui, "meshui", dbInfo = conn, commit = F)
    }

    # Remove any mesh descriptors that were not added to the database
    notAdded <- meshui[!meshui %in% result$meshui]

    if (length(notAdded) > 0) {
      warning(
        "The following meshui were not found are are ignored: ",
        paste(notAdded, collapse = ", ")
      )
    }

    # Insert new meshUI from papers
    meshArticle <- meshDescriptors |>
      select(
        arID,
        meshui = DescriptorUI,
        descriptorMajor = DescriptorMajor
      ) |>
      filter(!meshui %in% c(notAdded, "D008297", "D005260")) |>
      distinct() |>
      mutate(descriptorMajor = ifelse(descriptorMajor == "Y", 1, 0)) |>
      tbl_insert(conn, "mesh_article")
  }

  if (flagUpdate) {
    . <- dbFlagUpdate(1, dbInfo = conn, commit = F)
  }

  dbFinish(conn)

  return(arInfo %>% mutate(auID = {{ auID }}))
}

#' Delete specified articles and any associated authors / author names
#' Useful when an article has been incorrectly associated with an author for
#' example because of name overlap
#'
#' @param arIDs Vector of arIDs to delete (as found in article table)
#' @param dbInfo Connection to a Colabnet database
#' @param commit (Default = TRUE). Commit changes to the database automatically
#'
#' @import RSQLite
#' @import dplyr
#'
#' @return Dataframe of articles and authors/author names that have been deleted
#' @export
#'
dbDeleteArticle <- function(arIDs, dbInfo, commit = T) {
  conn <- dbGetConn(dbInfo, inherit = !commit)

  # Get all articles and authors to remove
  toRemove <- tbl(conn, "coAuthor") |>
    filter(arID %in% local(arIDs)) |>
    collect()

  # Keep author names that are in other articles not being removed
  toKeep <- tbl(conn, "coAuthor") |>
    filter(
      anID %in% local(unique(toRemove$anID)),
      !arID %in% local(unique(toRemove$arID))
    ) |>
    select(anID) |>
    distinct() |>
    pull(anID)

  toRemove <- toRemove |> filter(!anID %in% toKeep)

  # Authors with action deleteAuthor will be removed completely,
  #  authors with action deleteName only have a specific alternative/incorrect name removed
  removeAuth <- tbl(conn, "authorName") |>
    filter(auID %in% local(toRemove$auID)) |>
    distinct() |>
    collect() |>
    left_join(
      toRemove |> select(auID2 = auID, anID) |> distinct(),
      by = "anID"
    ) |>
    group_by(auID) |>
    mutate(
      action = ifelse(
        any(is.na(auID2)),
        "deleteName",
        "deleteAuthor"
      )
    ) |>
    ungroup() |>
    filter(!is.na(auID2))

  # Delete authors
  . <- removeAuth |>
    filter(action == "deleteAuthor") |>
    select(auID) |>
    unique() |>
    tbl_delete(conn, "author")

  # q <- dbExecute(
  #   conn,
  #   sprintf(
  #     "DELETE FROM author WHERE auID IN (%s)",
  #     paste(delAuID, collapse = ",")
  #   )
  # )

  # Delete incorrect names
  . <- removeAuth |>
    filter(action == "deleteName") |>
    seect(anID) |>
    unique() |>
    tbl_delete(conn, "authorName")

  # q <- dbExecute(
  #   conn,
  #   sprintf(
  #     "DELETE FROM authorName WHERE anID IN (%s)",
  #     paste(delAnID, collapse = ",")
  #   )
  # )

  # Delete articles
  . <- tbl_delete(data.frame(arID = arIDs), conn, "article")

  # q <- dbExecute(
  #   conn,
  #   sprintf(
  #     "DELETE FROM article WHERE arID IN (%s)",
  #     paste(arIDs, collapse = ",")
  #   )
  # )

  dbFinish(conn)

  return(removeAuth)
}
